version: '3.8'

services:
  publish:
    build: 
      context: ./publish
      dockerfile: Dockerfile
    container_name: publish
    hostname: publish
    environment:
      - PORT=6000
      - SUB_HOST=subscriber
    restart: always
    networks:
      - pubsub-network
    depends_on:
      - subscriber
  subscriber:
    build:
      context: ./subscriber
      dockerfile: Dockerfile
    container_name: subscriber
    hostname: subscriber
    ports:
      - "6000:6000"
    environment:
      - PORT=6000
    networks:
      - pubsub-network

networks:
  pubsub-network:
    driver: bridge